server {
    listen 80;

    location /_next/static/ {
        alias /app/.next/static/;
        expires 365d;
        access_log off;
    }

    location /public/ {
        alias /app/public/;
        expires 365d;
        access_log off;
    }

    location /api/ {
        proxy_pass http://tripdeal-backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
