apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripdeal-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: tripdeal-backend
  template:
    metadata:
      labels:
        app: tripdeal-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory }}
              cpu: {{ .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory }}
              cpu: {{ .Values.backend.resources.limits.cpu }}
          env:
            - name: SPRING_REDIS_HOST
              value: tripdeal-redis
            - name: DB_URL
              value: "jdbc:mysql://tripdeal-mysql:3306/tripdealdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: DB_USERNAME
              value: "tripdeal"
            - name: DB_PASSWORD
              value: "tripdeal1234"
            - name: DDL_AUTO
              value: "update"
