apiVersion: v1
kind: Service
metadata:
  name: tripdeal-backend
spec:
  selector:
    app: tripdeal-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tripdeal-frontend
spec:
  selector:
    app: tripdeal-frontend
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP
