apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripdeal-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: tripdeal-frontend
  template:
    metadata:
      labels:
        app: tripdeal-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory }}
              cpu: {{ .Values.frontend.resources.requests.cpu }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://tripdeal-backend:8080"
